Lesson_1
alfacentaur85/ASP.NETCoreWebApp pull request #1
Opened 2021-06-24 12:50 UTC by alfacentaur85

Lesson_1

2021-06-24 18:32 UTC, vladimir-shmidt requested changes
в целом код хороший
с асинком ок
есть пара моментов улучшить

2021-06-24 18:32 UTC, vladimir-shmidt commented on GetPost/GetPost/Program.cs
> +        static async Task MakeACallToPost(int id)
именование метода не соответствует доействиям в названии делать запрос а в действиях еще и писать в файл

2021-06-24 18:32 UTC, vladimir-shmidt commented on GetPost/GetPost/Program.cs
> +            var response = await _client.GetAsync($"https://jsonplaceholder.typicode.com/posts/{id}", _cts.Token);
при ошибке в любом из вызовов скачивания поста последующие посты не скачаются даже если с ними нет проблем
потеря одного запроса не должна приводить к крашу остальных

2021-06-24 18:32 UTC, vladimir-shmidt commented on GetPost/GetPost/Program.cs
> +                    Console.WriteLine("Cannot read to file...");
read from file? очепятка

2021-06-24 18:32 UTC, vladimir-shmidt commented on GetPost/GetPost/Program.cs
> +        static long GetFileLength(string filename)
метод нигде не используется

2021-06-24 18:32 UTC, vladimir-shmidt commented on GetPost/GetPost/Program.cs
> +        static void CreateFile()
файл не обязательно создавать что бы начаь запись в него. Обычно в методе записи модно установить флаг на создание файла в случае отсутствия

2021-06-24 18:32 UTC, vladimir-shmidt commented on GetPost/GetPost/Program.cs
> +                    await fstream.WriteAsync(array, 0, array.Length);
на выходе нужно полчить читаемый файл с текстом скачанных постов

2021-06-24 18:32 UTC, vladimir-shmidt commented on GetPost/GetPost/Program.cs
> +                    await fstream.WriteAsync(array, 0, array.Length);
бинарные данные не подойдут

2021-07-05 14:48 UTC, vladimir-shmidt requested changes
ожидать изменений?

2021-07-05 15:48 UTC, alfacentaur85 commented
Ой, если можно их вносить, то конечно. Я сегодня попозже поправлю, что смогу и закомичу05.07.2021, 17:48, "Vladimir Shmidt" ***@***.***>:
@vladimir-shmidt requested changes on this pull request.

ожидать изменений?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-05 16:11 UTC, alfacentaur85 commented
Здравствуйте, Владимир! Я внес корректировки и запушил коммит на гитхаб. Но хочу напомнить про свои пояснения от 24.06 на счет неподходимости бинарных данных:"Там же десериализация бинарного потока в объект пользовательского класса JsonStructure со string полями. И уже эти поля записываются в файл, поэтому всё читается из файла корректно. Т.е я бинарные данные в файл не пишу, а только читаю в поток с хоста/это мой польз клас для хранения экземпляров поста/JsonStructure{public string UserId { get; set; }public string Id { get; set; }public string Title { get; set; }public string Body { get; set; }}......................./десериализация и запись в файл string значений/var json = JsonConvert.DeserializeObject<JsonStructure>(content); await WriteToFile(String.Concat(json.UserId, "\n", json.Id, "\n", json.Title, "\n", json.Body,"\n\n")); }"05.07.2021, 17:48, "Vladimir Shmidt" ***@***.***>:
@vladimir-shmidt requested changes on this pull request.

ожидать изменений?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-05 20:53 UTC, vladimir-shmidt commented
Привет! Ссори виидмо уехали старые комменты с запросом на изменения с прошлого раза. По записи в файл понял

2021-07-05 21:27 UTC, vladimir-shmidt approved these changes
отлично

2021-07-06 06:45 UTC, closed without merging